#cloud-config
# - Required Extra Vars
# $INTERFACE
# $STATIC_IP_ADDRESS
# $GATEWAY_IP
# $DNS_SERVER_IP
# $EDITOR_VERSION
hostname: ${VM_NAME}
fqdn: ${VM_NAME}
disable_root: false
network:
  config: disabled
users:
  - name: ${USERNAME}
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_import_id:
      - gh:${GITHUB_USER}
  - name: ${VM_ADMIN}
    gecos: system acct
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_authorized_keys:
      - ${VM_KEY}
write_files:
- path: /etc/netplan/99-my-new-config.yaml
  permissions: '0644'
  content: |
    network:
      ethernets:
        ${INTERFACE}:
          dhcp4: no
          dhcp6: no
          addresses: [${STATIC_IP_ADDRESS}/24]
          routes:
            - to: default
              via: ${GATEWAY_IP}
          mtu: 1500
          nameservers:
            addresses: [${DNS_SERVER_IP}]
      renderer: networkd
      version: 2
- path: /etc/unity-hub
  permissions: '0644'
  content: |
    #!/bin/bash
    xvfb-run -ae /dev/stdout /opt/unityhub/unityhub-bin --no-sandbox --headless "\$@"
snap:
  commands:
    00: ['install', '--beta', 'steam']
    01: ['install', 'firefox']
    # We have to use the snap version of firefox because the apt-version is not correctly 
    # detected as the system default which causes errors when unity-hub tries to authenticate
apt:
  primary:
    - arches: [default]
      uri: http://us.archive.ubuntu.com/ubuntu/
  sources:
    unityhub.list:
      source: deb https://hub.unity3d.com/linux/repos/deb stable main
package_update: true
package_upgrade: true
runcmd:
  #---Updating network config for use with static ip addressing---
  - netplan --degug generate
  - netplan --debug apply

