#cloud-config
# - Required Extra Vars
# $INTERFACE
# $STATIC_IP_ADDRESS
# $GATEWAY_IP
# $DNS_SERVER_IP
# $EDITOR_VERSION
hostname: ${VM_NAME}
fqdn: ${VM_NAME}
disable_root: false
network:
  config: disabled
users:
  - name: ${USERNAME}
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_import_id:
      - gh:${GITHUB_USER}
  - name: ${VM_ADMIN}
    gecos: system acct
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: ${PASSWD}
    ssh_authorized_keys:
      - ${VM_KEY}
write_files:
- path: /etc/netplan/99-my-new-config.yaml
  permissions: '0644'
  content: |
    network:
      ethernets:
        ${INTERFACE}:
          dhcp4: no
          dhcp6: no
          addresses: [${STATIC_IP_ADDRESS}/24]
          routes:
            - to: default
              via: ${GATEWAY_IP}
          mtu: 1500
          nameservers:
            addresses: [${DNS_SERVER_IP}]
      renderer: networkd
      version: 2
- path: /etc/unity-hub
  permissions: '0644'
  content: |
    #!/bin/bash
    xvfb-run -ae /dev/stdout /opt/unityhub/unityhub-bin --no-sandbox --headless "\$@"
snap:
  commands:
    00: ['install', '--beta', 'steam']
    01: ['install', 'firefox']
    # We have to use the snap version of firefox because the apt-version is not correctly 
    # detected as the system default which causes errors when unity-hub tries to authenticate
apt:
  primary:
    - arches: [default]
      uri: http://us.archive.ubuntu.com/ubuntu/
  sources:
    unityhub.list:
      source: deb https://hub.unity3d.com/linux/repos/deb stable main
package_update: true
package_upgrade: true
packages:
  - apt-utils
  - ca-certificates
  - libasound2
  - libc6-dev
  - libcap2
  - libgconf-2-4
  - libglu1
  - libgtk-3-0
  - libncurses5
  - libnotify4
  - libnss3
  - libxtst6
  - libxss1
  - cpio
  - lsb-release
  - python3-pip
  - docker.io
  - python-setuptools
  - xz-utils
  - atop
  - curl
  - git
  - git-lfs
  - jq
  - openssh-client
  - wget
  - software-properties-common  
  - zenity
  - libgbm1
  - gnupg
  - x11vnc
  - ubuntu-desktop
  - xvfb
  - xterm
  - net-tools
  - ubuntu-drivers-common 
  - linux-headers-generic
  # workaround for https://askubuntu.com/questions/1436601/ubuntu-drivers-unboundlocalerror-local-variable-version-referenced-before-as
bootcmd:
  - mkdir -p "/opt/unityhub/chrome-sandbox"
  - mkdir -p "/opt/unity/editors"
runcmd:
  #---Updating network config for use with static ip addressing---
  - netplan --degug generate
  - netplan --debug apply
  - rm /etc/netplan/50*
  #---Downloading xorg.conf---"
  - curl https://raw.githubusercontent.com/cloudymax/Scrap-Metal/main/virtual-machines/qemu/configs/xorg.conf.headless > /tmp/xorg.conf
  - cp /tmp/xorg.conf /etc/X11/xorg.conf 
  #---installing older version of SSL as workaround for Unity Hub failing to launch---
  - wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  - sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  - rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb
  #---Downloading Unity's Apt Key manually since its not in the Ubuntu keyserver---
  - wget -qO- https://hub.unity3d.com/linux/keys/public | apt-key add -
  #---Installing UnityHub---
  - apt-get update -y
  - apt-get install -y unityhub
  - mv /etc/unity-hub /usr/bin/unity-hub
  #--- Doanload and install Unity Editor version 2022.1.23f1---
  - sudo xvfb-run -ae /dev/stdout /opt/unityhub/unityhub-bin --no-sandbox --headless install-path --set "/opt/unity/editors"
  - sudo xvfb-run -ae /dev/stdout /opt/unityhub/unityhub-bin --no-sandbox --headless install -v 2022.1.23f1
  #---installing git lfs---
  - git lfs install --system --skip-repo
  #---Setting SSH port and options---
  - sed -i -e '/^Port/s/^.*$/Port 22/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  - ubuntu-drivers install nvidia:525
